# Tensorflow exercices

Exercise 1: Create a TensorFlow constant tensor with values [1, 2, 3, 4, 5].

In [12]:
import tensorflow as tf

tensor = tf.constant([1,2,3,4,5], dtype=tf.float32)

print(tensor)

tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float32)


Exercise 2: Create a TensorFlow variable tensor initialized with zeros of shape (3, 3).

In [13]:
tensor_2 = tf.Variable(tf.zeros((3, 3)))

print(tensor_2)

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>


Exercise 3: Perform matrix multiplication of two TensorFlow constant tensors A and B.

In [14]:

A = tf.constant([[5, 2], [4, 4]])
B = tf.constant([[7, 6], [7, 8]])
C = tf.matmul(A, B)

print(C)


tf.Tensor(
[[49 46]
 [56 56]], shape=(2, 2), dtype=int32)


Exercise 4: Create a TensorFlow placeholder for a scalar value.

Exercise 5: Define a TensorFlow operation to compute the element-wise product of two tensors.

In [16]:

tensor_a = tf.constant([1, 2, 3])
tensor_b = tf.constant([4, 5, 6])
elementwise_product = tf.multiply(tensor_a, tensor_b)
print(elementwise_product)


tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


Exercise 6: Create a TensorFlow graph to compute the mean of a given tensor along a specified axis.

In [17]:

tensor_3 = tf.constant([[1, 2, 3], [4, 5, 6]])
mean_tensor = tf.reduce_mean(tensor_3, axis=0)
print(mean_tensor)


tf.Tensor([2 3 4], shape=(3,), dtype=int32)


Exercise 7: Implement a simple linear regression model using TensorFlow.

In [22]:


# Generating some sample data
X_train = tf.constant([1, 2, 3, 4, 5], dtype=tf.float32)
y_train = tf.constant([2, 4, 6, 8, 10], dtype=tf.float32)

# Variables
W = tf.Variable(0.0)
b = tf.Variable(0.0)

# Linear regression model
def linear_regression(X):
    return W * X + b

# Loss function (MSE: low MSE indicates better model performance)
def mean_squared_error(y_true, y_pred):
    return tf.reduce_mean(tf.square(y_true - y_pred))

# Optimizer (Stochastic Gradient Descent)
optimizer = tf.optimizers.SGD(learning_rate=0.01)

# Training function (comput predictions, calculate loss, computes gradients and updates parameters)
def train_step(X, y):
    with tf.GradientTape() as tape: #records operations for automatic differentiation
        predictions = linear_regression(X)
        loss = mean_squared_error(y, predictions)
    gradients = tape.gradient(loss, [W, b]) #computes the gradients of the loss with respect to the model parameters W and b
    optimizer.apply_gradients(zip(gradients, [W, b])) #The gradients computed in the previous step are used to update the model parameters (W and b) 
    return loss

# Training loop
for epoch in range(1000):
    loss = train_step(X_train, y_train)
    if epoch % 100 == 0: #print per 100
        print(f'Epoch {epoch}: Loss: {loss.numpy()}')

print(f'Final W: {W.numpy()}, b: {b.numpy()}')


Epoch 0: Loss: 44.0


Epoch 100: Loss: 0.024474427103996277
Epoch 200: Loss: 0.012432219460606575
Epoch 300: Loss: 0.006315155886113644
Epoch 400: Loss: 0.003207895439118147
Epoch 500: Loss: 0.001629501348361373
Epoch 600: Loss: 0.0008277297019958496
Epoch 700: Loss: 0.00042046388261951506
Epoch 800: Loss: 0.00021357601508498192
Epoch 900: Loss: 0.0001084920804714784
Final W: 1.995180368423462, b: 0.01740049012005329


Exercise 8: Create a TensorFlow dataset from a NumPy array.

In [19]:
import numpy as np

numpy_array = np.array([1, 2, 3, 4, 5])
dataset = tf.data.Dataset.from_tensor_slices(numpy_array)
for element in dataset:
    print(element)


tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)


2024-05-30 14:10:27.291172: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int64 and shape [5]
	 [[{{node Placeholder/_0}}]]


Exercise 9: Define a custom TensorFlow function using tf.function decorator.

In [1]:
import tensorflow as tf

@tf.function
def my_function(x, y):
    return x * y + y

# Using the function
a = tf.constant(2)
b = tf.constant(3)

result = my_function(a, b)
print(result)  # Output will be a TensorFlow tensor


2024-05-30 17:25:58.412721: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


tf.Tensor(9, shape=(), dtype=int32)


Exercise 10: Load and preprocess an image using TensorFlow.

In [23]:


def load_and_preprocess_image(path):
    image = tf.io.read_file(path)
    image = tf.image.decode_jpeg(image, channels=3)
    image = tf.image.resize(image, [224, 224])
    image = image / 255.0  # Normalize to [0,1]
    return image

image_path = 'dog.jpeg'
image = load_and_preprocess_image(image_path)
print(image.shape)


(224, 224, 3)


Exercise 11: Neural Network
Build and train a neural network with one hidden layer on the MNIST dataset.

In [24]:

from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.models import Sequential

# Load MNIST dataset
mnist = tf.keras.datasets.mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()

# Normalize data
X_train, X_test = X_train / 255.0, X_test / 255.0

# Build model
model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

# Compile model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Train model
model.fit(X_train, y_train, epochs=5)

# Evaluate model
test_loss, test_acc = model.evaluate(X_test, y_test)
print(f'Test accuracy: {test_acc}')


Epoch 1/5
1875/1875 [==============================] - 11s 5ms/step - loss: 0.2581 - accuracy: 0.9266
Epoch 2/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1142 - accuracy: 0.9668
Epoch 3/5
1875/1875 [==============================] - 10s 6ms/step - loss: 0.0803 - accuracy: 0.9761
Epoch 4/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0599 - accuracy: 0.9819
Epoch 5/5
313/313 [==============================] - 1s 3ms/step - loss: 0.0805 - accuracy: 0.9745
Test accuracy: 0.9745000004768372
